/**
 * Static destination data used before Supabase is connected.
 * This mirrors the seed.sql data so the app works without a database.
 */

import type { DestinationRow } from "./destinations-context";

export const SEED_DESTINATIONS: DestinationRow[] = [
  {
    slug: "tokyo",
    name: "Tokyo",
    region: "kanto",
    description: "Japan's massive capital blends ultramodern and traditional, from neon-lit skyscrapers and anime shops to historic temples and serene gardens.",
    highlights: ["Shibuya Crossing", "Senso-ji Temple", "Tsukiji Outer Market", "Akihabara", "Meiji Shrine", "TeamLab Borderless"],
    best_seasons: ["spring", "autumn"],
    crowd_level_by_month: {"1":3,"2":3,"3":4,"4":5,"5":4,"6":3,"7":4,"8":4,"9":3,"10":4,"11":4,"12":4},
    tags: ["shopping", "food", "nightlife", "culture", "temples"],
    jr_accessible: true,
    reservation_tips: "Book TeamLab tickets 2-3 weeks ahead. Popular restaurants in Ginza/Shibuya need reservations. Sumo tournament tickets sell out months in advance (Jan, May, Sep).",
    accommodation_zones: [
      { name: "Shinjuku", description: "Central hub with great train access, nightlife, and hotels at every price point", best_for: ["nightlife", "first-timers", "transit"] },
      { name: "Shibuya", description: "Trendy area with shopping, dining, and iconic crossing", best_for: ["shopping", "young travelers", "couples"] },
      { name: "Asakusa", description: "Traditional neighborhood near Senso-ji, budget-friendly", best_for: ["culture", "budget", "temples"] },
      { name: "Ginza", description: "Upscale district with luxury shopping and fine dining", best_for: ["luxury", "shopping", "couples"] },
    ],
    image: "https://plus.unsplash.com/premium_photo-1749757898790-d8528d52049b?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "kyoto",
    name: "Kyoto",
    region: "kansai",
    description: "The cultural heart of Japan with over 2,000 temples and shrines, traditional geisha districts, and exquisite kaiseki cuisine.",
    highlights: ["Fushimi Inari Shrine", "Kinkaku-ji", "Arashiyama Bamboo Grove", "Gion District", "Nishiki Market", "Kiyomizu-dera"],
    best_seasons: ["spring", "autumn"],
    crowd_level_by_month: {"1":2,"2":2,"3":4,"4":5,"5":4,"6":3,"7":3,"8":3,"9":3,"10":4,"11":5,"12":3},
    tags: ["temples", "culture", "food", "nature", "shopping", "nightlife"],
    jr_accessible: true,
    reservation_tips: "Book ryokans 2-3 months ahead during cherry blossom (late Mar-Apr) and autumn foliage (Nov). Some temples require advance booking.",
    accommodation_zones: [
      { name: "Downtown (Kawaramachi/Gion)", description: "Central location near shopping, restaurants, and Gion geisha district", best_for: ["nightlife", "food", "culture", "first-timers"] },
      { name: "Higashiyama", description: "Eastern hills area surrounded by temples", best_for: ["temples", "culture", "walking"] },
      { name: "Arashiyama", description: "Western district with bamboo grove and monkey park", best_for: ["nature", "couples"] },
      { name: "Kyoto Station area", description: "Transit hub, convenient for day trips", best_for: ["transit", "budget"] },
    ],
    image: "https://plus.unsplash.com/premium_photo-1673285285994-6bfff235db97?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "osaka",
    name: "Osaka",
    region: "kansai",
    description: "Japan's kitchen and comedy capital. Known for incredible street food, vibrant nightlife, and a laid-back, friendly atmosphere.",
    highlights: ["Dotonbori", "Osaka Castle", "Shinsekai", "Kuromon Market", "Universal Studios Japan", "Namba"],
    best_seasons: ["spring", "autumn"],
    crowd_level_by_month: {"1":3,"2":3,"3":4,"4":4,"5":4,"6":3,"7":4,"8":4,"9":3,"10":4,"11":4,"12":3},
    tags: ["food", "nightlife", "shopping", "culture"],
    jr_accessible: true,
    reservation_tips: "Book Universal Studios tickets online in advance. Most street food spots are walk-in. Reserve high-end sushi/kappo restaurants ahead.",
    accommodation_zones: [
      { name: "Namba/Dotonbori", description: "Heart of Osaka nightlife and street food, always buzzing", best_for: ["nightlife", "food", "first-timers"] },
      { name: "Umeda/Kita", description: "Business district with upscale dining and shopping", best_for: ["luxury", "shopping"] },
      { name: "Shinsekai", description: "Retro neighborhood famous for kushikatsu and local vibes", best_for: ["food", "budget", "culture"] },
    ],
    image: "https://plus.unsplash.com/premium_photo-1724593825200-39731dcdacf8?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "hakone",
    name: "Hakone",
    region: "chubu",
    description: "Hot spring resort town in the mountains near Mt. Fuji, with open-air museums, lake cruises, and traditional ryokans.",
    highlights: ["Hakone Open-Air Museum", "Lake Ashi cruise", "Owakudani volcanic valley", "Mt. Fuji views", "Onsen ryokans"],
    best_seasons: ["autumn", "spring", "winter"],
    crowd_level_by_month: {"1":2,"2":2,"3":3,"4":4,"5":3,"6":2,"7":3,"8":4,"9":2,"10":4,"11":4,"12":2},
    tags: ["onsen", "nature", "culture"],
    jr_accessible: true,
    reservation_tips: "Book ryokans with private onsen well in advance, especially weekends. Get the Hakone Free Pass for transport savings.",
    accommodation_zones: [
      { name: "Hakone-Yumoto", description: "Main gateway town with many ryokans and easy access", best_for: ["onsen", "convenience"] },
      { name: "Gora/Sounzan area", description: "Higher elevation with mountain views and quieter atmosphere", best_for: ["nature", "luxury", "couples"] },
    ],
    image: "https://plus.unsplash.com/premium_photo-1723054810919-e181b7efa764?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "hiroshima",
    name: "Hiroshima",
    region: "chugoku",
    description: "A city of resilience and peace, home to the atomic bomb memorial, incredible okonomiyaki, and gateway to Miyajima Island.",
    highlights: ["Peace Memorial Park", "Atomic Bomb Dome", "Miyajima Island", "Itsukushima Shrine", "Hiroshima-style okonomiyaki"],
    best_seasons: ["spring", "autumn"],
    crowd_level_by_month: {"1":2,"2":2,"3":3,"4":4,"5":3,"6":2,"7":3,"8":3,"9":2,"10":3,"11":4,"12":2},
    tags: ["culture", "food", "temples", "nature"],
    jr_accessible: true,
    reservation_tips: "Miyajima has limited accommodation — book ryokans well ahead if staying overnight. The floating torii gate is best at high tide.",
    accommodation_zones: [
      { name: "Peace Park area", description: "Central, walkable to main sights and okonomiyaki street", best_for: ["culture", "convenience", "first-timers"] },
      { name: "Miyajima Island", description: "Stay overnight to see the shrine without day-trip crowds", best_for: ["temples", "couples", "nature"] },
    ],
    image: "https://plus.unsplash.com/premium_photo-1751729232888-8c7a7f594b48?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "nara",
    name: "Nara",
    region: "kansai",
    description: "Ancient capital home to friendly free-roaming deer, massive bronze Buddha, and some of Japan's oldest wooden buildings.",
    highlights: ["Todai-ji Temple", "Nara Deer Park", "Kasuga Grand Shrine", "Isuien Garden", "Naramachi"],
    best_seasons: ["spring", "autumn"],
    crowd_level_by_month: {"1":2,"2":2,"3":3,"4":4,"5":3,"6":2,"7":3,"8":3,"9":2,"10":3,"11":3,"12":2},
    tags: ["temples", "culture", "nature"],
    jr_accessible: true,
    reservation_tips: "No reservations needed for main sights. Easy day trip from Kyoto or Osaka (30-45 min by train).",
    accommodation_zones: [
      { name: "Near Nara Park", description: "Walking distance to deer park and temples", best_for: ["convenience", "culture"] },
    ],
    image: "https://plus.unsplash.com/premium_photo-1742948213097-7b1d9078bb1b?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "kamakura",
    name: "Kamakura",
    region: "kanto",
    description: "Coastal town south of Tokyo known for its Great Buddha, historic temples, and beach vibes. A perfect day trip or overnight from the capital.",
    highlights: ["Great Buddha (Kotoku-in)", "Tsurugaoka Hachimangu", "Hase-dera Temple", "Enoshima Island", "Komachi-dori Street"],
    best_seasons: ["spring", "autumn"],
    crowd_level_by_month: {"1":2,"2":2,"3":3,"4":4,"5":3,"6":3,"7":4,"8":4,"9":3,"10":3,"11":3,"12":2},
    tags: ["temples", "culture", "beach", "nature"],
    jr_accessible: true,
    reservation_tips: "No major reservations needed. Go early on weekends to avoid crowds at the Great Buddha.",
    accommodation_zones: [
      { name: "Kamakura Station area", description: "Walking distance to temples and Komachi-dori shopping street", best_for: ["convenience", "culture"] },
    ],
    image: "https://images.unsplash.com/photo-1669954435562-94c02d3246cf?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "nikko",
    name: "Nikko",
    region: "kanto",
    description: "Mountain town famous for the ornate Toshogu Shrine (a UNESCO site), stunning autumn foliage, and natural hot springs.",
    highlights: ["Toshogu Shrine", "Kegon Falls", "Lake Chuzenji", "Shinkyo Bridge", "Kanmangafuchi Abyss"],
    best_seasons: ["autumn", "spring"],
    crowd_level_by_month: {"1":1,"2":1,"3":2,"4":3,"5":3,"6":2,"7":3,"8":3,"9":2,"10":5,"11":4,"12":1},
    tags: ["temples", "nature", "onsen", "culture"],
    jr_accessible: true,
    reservation_tips: "Buy the Nikko All-Area Pass for bus and train discounts. Toshogu gets crowded mid-day — go early.",
    accommodation_zones: [
      { name: "Nikko town center", description: "Near the shrines and main attractions", best_for: ["convenience", "culture"] },
    ],
    image: "https://plus.unsplash.com/premium_photo-1678249204369-d7582731335d?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "nagoya",
    name: "Nagoya",
    region: "chubu",
    description: "Japan's fourth-largest city and a major transport hub. Known for its unique food culture (miso everything), Toyota heritage, Nagoya Castle, and easy access to the Japanese Alps.",
    highlights: ["Nagoya Castle", "Atsuta Shrine", "Osu Kannon & Shopping", "Toyota Museum", "Miso Katsu & Hitsumabushi"],
    best_seasons: ["spring", "autumn"],
    crowd_level_by_month: {"1":2,"2":2,"3":3,"4":3,"5":3,"6":2,"7":3,"8":3,"9":2,"10":3,"11":3,"12":2},
    tags: ["food", "culture", "shopping"],
    jr_accessible: true,
    reservation_tips: "Atsuta Horaiken (hitsumabushi) is always packed — go at opening or expect a wait. Castle admission is timed.",
    accommodation_zones: [
      { name: "Nagoya Station area", description: "Major transport hub with easy Shinkansen access", best_for: ["transit", "budget", "convenience"] },
      { name: "Sakae", description: "Central shopping and entertainment district with restaurants and nightlife", best_for: ["shopping", "nightlife", "food"] },
    ],
    image: "https://images.unsplash.com/photo-1648534092296-272a36375e45?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "takayama",
    name: "Takayama",
    region: "chubu",
    description: "Beautifully preserved Edo-era merchant town in the Japanese Alps, known for morning markets, sake, and Hida beef.",
    highlights: ["Old Town (Sanmachi Suji)", "Morning Markets", "Hida Folk Village", "Hida Beef", "Sake Breweries"],
    best_seasons: ["spring", "autumn", "winter"],
    crowd_level_by_month: {"1":2,"2":2,"3":3,"4":4,"5":3,"6":2,"7":3,"8":3,"9":2,"10":4,"11":3,"12":2},
    tags: ["culture", "food", "nature", "onsen"],
    jr_accessible: true,
    reservation_tips: "During Takayama Festival (Apr & Oct), book accommodation months ahead. Morning markets run daily.",
    accommodation_zones: [
      { name: "Old Town area", description: "Walking distance to Sanmachi Suji, markets, and breweries", best_for: ["culture", "food", "walking"] },
    ],
    image: "https://images.unsplash.com/photo-1662138589066-d627f283cde4?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "kanazawa",
    name: "Kanazawa",
    region: "chubu",
    description: "The 'Little Kyoto' on the Sea of Japan coast, with one of Japan's top three gardens, samurai districts, and fresh seafood.",
    highlights: ["Kenroku-en Garden", "Higashi Chaya District", "Omicho Market", "21st Century Museum", "Nagamachi Samurai District"],
    best_seasons: ["spring", "autumn", "winter"],
    crowd_level_by_month: {"1":2,"2":2,"3":3,"4":3,"5":3,"6":2,"7":3,"8":3,"9":2,"10":3,"11":3,"12":2},
    tags: ["culture", "food", "nature", "shopping"],
    jr_accessible: true,
    reservation_tips: "Most attractions are walk-in. Try to visit Omicho Market on weekdays for a calmer experience.",
    accommodation_zones: [
      { name: "Central Kanazawa", description: "Near Kenroku-en and the main attractions, walkable", best_for: ["convenience", "culture"] },
    ],
    image: "https://images.unsplash.com/photo-1637846931849-d1748990481b?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "sapporo",
    name: "Sapporo",
    region: "hokkaido",
    description: "Hokkaido's capital, famous for its snow festival, miso ramen, fresh seafood, beer, and nearby ski resorts.",
    highlights: ["Sapporo Snow Festival", "Nijo Market", "Odori Park", "Sapporo Beer Museum", "Susukino nightlife", "Ramen Alley"],
    best_seasons: ["winter", "summer"],
    crowd_level_by_month: {"1":4,"2":5,"3":3,"4":2,"5":2,"6":2,"7":4,"8":4,"9":2,"10":2,"11":2,"12":3},
    tags: ["food", "nightlife", "skiing", "culture", "nature"],
    jr_accessible: true,
    reservation_tips: "Snow Festival (early Feb) requires booking hotels 3+ months ahead. Ramen Alley is walk-in.",
    accommodation_zones: [
      { name: "Odori/Tanukikoji", description: "Central area near parks, shopping, and attractions", best_for: ["convenience", "shopping", "first-timers"] },
      { name: "Susukino", description: "Nightlife and entertainment district", best_for: ["nightlife", "food"] },
    ],
    image: "https://images.unsplash.com/photo-1755789487714-5a681b890406?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "niseko",
    name: "Niseko",
    region: "hokkaido",
    description: "World-class powder snow destination and growing summer adventure hub with rafting, hiking, and golf.",
    highlights: ["Powder skiing", "Mt. Yotei views", "Onsen after skiing", "Summer rafting", "Local craft beer"],
    best_seasons: ["winter"],
    crowd_level_by_month: {"1":5,"2":4,"3":3,"4":1,"5":1,"6":1,"7":2,"8":2,"9":1,"10":1,"11":1,"12":4},
    tags: ["skiing", "adventure", "onsen", "nature"],
    jr_accessible: false,
    reservation_tips: "Book ski accommodation and lift passes well in advance for Dec-Feb.",
    accommodation_zones: [
      { name: "Hirafu Village", description: "Main village with most restaurants, bars, and ski access", best_for: ["skiing", "nightlife", "convenience"] },
    ],
    image: "https://images.unsplash.com/photo-1646440135621-288cad46d1fe?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "fukuoka",
    name: "Fukuoka",
    region: "kyushu",
    description: "Kyushu's largest city, famous for its yatai (street food stalls), tonkotsu ramen, beaches, and relaxed atmosphere.",
    highlights: ["Yatai street food stalls", "Canal City", "Ohori Park", "Dazaifu Tenmangu", "Hakata Ramen"],
    best_seasons: ["spring", "autumn"],
    crowd_level_by_month: {"1":2,"2":2,"3":3,"4":3,"5":3,"6":3,"7":3,"8":3,"9":2,"10":3,"11":3,"12":2},
    tags: ["food", "nightlife", "culture", "beach"],
    jr_accessible: true,
    reservation_tips: "Yatai stalls are first-come, first-served — go around 7-8pm for best selection.",
    accommodation_zones: [
      { name: "Tenjin/Nakasu", description: "Central entertainment district with yatai stalls along the river", best_for: ["nightlife", "food", "first-timers"] },
      { name: "Hakata Station area", description: "Transit hub, convenient for bullet train travel", best_for: ["transit", "convenience"] },
    ],
    image: "https://images.unsplash.com/photo-1685845285281-94f706da0907?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "okinawa-main",
    name: "Okinawa (Main Island)",
    region: "okinawa",
    description: "Subtropical paradise with turquoise beaches, unique Ryukyu culture, American influence, and some of Japan's best diving.",
    highlights: ["Shuri Castle", "Churaumi Aquarium", "Kokusai Street", "American Village", "Blue cave snorkeling", "Okinawan cuisine"],
    best_seasons: ["spring", "summer"],
    crowd_level_by_month: {"1":2,"2":2,"3":3,"4":3,"5":3,"6":3,"7":5,"8":5,"9":3,"10":3,"11":2,"12":2},
    tags: ["beach", "food", "culture", "nature", "adventure"],
    jr_accessible: false,
    reservation_tips: "Rent a car — public transport is limited outside Naha. Book diving/snorkeling tours ahead in summer.",
    accommodation_zones: [
      { name: "Naha", description: "Capital city with Kokusai Street, nightlife, and Shuri Castle", best_for: ["nightlife", "food", "culture", "budget"] },
      { name: "Chatan/American Village", description: "Mid-island area with beaches, shopping, and resort hotels", best_for: ["beach", "family", "shopping"] },
    ],
    image: "https://images.unsplash.com/photo-1754228781615-cc3d79670b0e?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "kobe",
    name: "Kobe",
    region: "kansai",
    description: "Port city famous for Kobe beef, sake breweries in Nada, vibrant Chinatown, and mountain-harbor scenery.",
    highlights: ["Kobe Beef tasting", "Nada sake district", "Nankinmachi Chinatown", "Nunobiki Herb Garden", "Meriken Park"],
    best_seasons: ["spring", "autumn"],
    crowd_level_by_month: {"1":2,"2":2,"3":3,"4":3,"5":3,"6":2,"7":3,"8":3,"9":2,"10":3,"11":3,"12":2},
    tags: ["food", "culture", "nature", "nightlife"],
    jr_accessible: true,
    reservation_tips: "Reserve Kobe beef restaurants at least a week ahead, especially on weekends.",
    accommodation_zones: [
      { name: "Sannomiya/Motomachi", description: "Central district with shopping, Chinatown, nightlife, and restaurants", best_for: ["food", "shopping", "nightlife", "convenience"] },
    ],
    image: "https://images.unsplash.com/photo-1706172216985-a7fdb4efcfc8?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "mt-fuji",
    name: "Mt. Fuji Area",
    region: "chubu",
    description: "Japan's iconic volcanic peak and surrounding Five Lakes region. Climbing season is short but the views are year-round.",
    highlights: ["Fuji Five Lakes", "Chureito Pagoda", "Kawaguchiko", "Fuji climbing (Jul-Sep)", "Oshino Hakkai"],
    best_seasons: ["summer", "autumn"],
    crowd_level_by_month: {"1":2,"2":2,"3":2,"4":3,"5":3,"6":3,"7":5,"8":5,"9":3,"10":4,"11":3,"12":2},
    tags: ["nature", "adventure", "onsen"],
    jr_accessible: true,
    reservation_tips: "Climbing season is July-September only. Mountain hut reservations required. Kawaguchiko area is accessible year-round.",
    accommodation_zones: [
      { name: "Kawaguchiko", description: "Lake town with Fuji views, onsen, and museums", best_for: ["nature", "onsen", "couples"] },
    ],
    image: "https://plus.unsplash.com/premium_photo-1723196718472-be6b6a214845?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "beppu",
    name: "Beppu",
    region: "kyushu",
    description: "One of Japan's top onsen towns with more hot spring sources than anywhere else in the country.",
    highlights: ["Beppu Hells", "Sand baths", "Onsen hopping", "Jigoku Mushi (hell-steamed cooking)", "Kannawa area"],
    best_seasons: ["autumn", "winter", "spring"],
    crowd_level_by_month: {"1":2,"2":2,"3":3,"4":3,"5":2,"6":2,"7":3,"8":3,"9":2,"10":3,"11":3,"12":2},
    tags: ["onsen", "nature", "food"],
    jr_accessible: true,
    reservation_tips: "Most onsen are walk-in. Beppu Hells combo ticket available on-site.",
    accommodation_zones: [
      { name: "Kannawa area", description: "Traditional onsen town with steam vents and ryokans", best_for: ["onsen", "culture"] },
    ],
    image: "https://images.unsplash.com/photo-1752917870379-ed88be3c2050?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "naoshima",
    name: "Naoshima",
    region: "shikoku",
    description: "Art island in the Seto Inland Sea featuring world-class museums, outdoor installations, and the iconic yellow pumpkin.",
    highlights: ["Chichu Art Museum", "Benesse House", "Yayoi Kusama Pumpkin", "Art House Project", "Lee Ufan Museum"],
    best_seasons: ["spring", "autumn", "summer"],
    crowd_level_by_month: {"1":1,"2":1,"3":3,"4":3,"5":3,"6":2,"7":3,"8":3,"9":2,"10":3,"11":3,"12":1},
    tags: ["culture", "nature"],
    jr_accessible: false,
    reservation_tips: "Chichu Art Museum requires timed-entry tickets — book online in advance. Some art houses are closed Mondays.",
    accommodation_zones: [
      { name: "Honmura area", description: "Village with Art House Project installations", best_for: ["culture", "budget"] },
    ],
    image: "https://images.unsplash.com/photo-1577814575782-51b1e900b8c7?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "yakushima",
    name: "Yakushima",
    region: "kyushu",
    description: "UNESCO World Heritage island with ancient cedar forests that inspired Princess Mononoke. A paradise for hikers.",
    highlights: ["Jomon Sugi (ancient cedar)", "Shiratani Unsuikyo Ravine", "Yakusugi Land", "Sea turtle nesting", "Oko Falls"],
    best_seasons: ["spring", "autumn"],
    crowd_level_by_month: {"1":1,"2":1,"3":2,"4":2,"5":3,"6":3,"7":3,"8":3,"9":2,"10":2,"11":2,"12":1},
    tags: ["nature", "adventure"],
    jr_accessible: false,
    reservation_tips: "Book ferry or flights early. Hire a guide for the Jomon Sugi hike (10+ hours).",
    accommodation_zones: [
      { name: "Miyanoura/Anbou", description: "Port towns with most accommodation and restaurants", best_for: ["convenience"] },
    ],
    image: "https://images.unsplash.com/photo-1723536415988-318f84346aac?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "shirakawa-go",
    name: "Shirakawa-go",
    region: "chubu",
    description: "UNESCO World Heritage village of traditional thatched-roof farmhouses in a mountain valley. Magical in winter snow.",
    highlights: ["Gassho-zukuri farmhouses", "Shiroyama Viewpoint", "Wada House", "Winter light-up event"],
    best_seasons: ["winter", "autumn", "spring"],
    crowd_level_by_month: {"1":4,"2":4,"3":2,"4":2,"5":2,"6":2,"7":3,"8":3,"9":2,"10":3,"11":3,"12":3},
    tags: ["culture", "nature"],
    jr_accessible: false,
    reservation_tips: "Winter light-up events require a lottery reservation months in advance.",
    accommodation_zones: [
      { name: "In the village", description: "Stay in a traditional farmhouse for the full experience", best_for: ["culture", "couples"] },
    ],
    image: "https://plus.unsplash.com/premium_photo-1661883132712-58b38588abbb?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "koyasan",
    name: "Koya-san",
    region: "kansai",
    description: "Sacred mountaintop monastery town and center of Shingon Buddhism. Stay in a temple, eat shojin ryori, and walk the ancient cemetery at night.",
    highlights: ["Okunoin Cemetery", "Kongobu-ji Temple", "Temple lodging (shukubo)", "Shojin ryori", "Danjo Garan"],
    best_seasons: ["autumn", "spring"],
    crowd_level_by_month: {"1":1,"2":1,"3":2,"4":3,"5":3,"6":2,"7":2,"8":2,"9":2,"10":4,"11":4,"12":1},
    tags: ["temples", "culture", "nature"],
    jr_accessible: true,
    reservation_tips: "Book temple lodging (shukubo) well in advance — there are no regular hotels.",
    accommodation_zones: [
      { name: "Central Koya-san", description: "Near Okunoin and main temples, all accommodation is temple lodging", best_for: ["culture", "temples"] },
    ],
    image: "https://plus.unsplash.com/premium_photo-1715030289259-95d728532ee0?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "matsumoto",
    name: "Matsumoto",
    region: "chubu",
    description: "Gateway to the Japanese Alps with one of Japan's most beautiful original castles and a charming art-focused downtown.",
    highlights: ["Matsumoto Castle", "Kamikochi Alpine Valley", "Nawate-dori Street", "Japan Ukiyo-e Museum"],
    best_seasons: ["summer", "autumn", "spring"],
    crowd_level_by_month: {"1":1,"2":1,"3":2,"4":3,"5":3,"6":2,"7":4,"8":4,"9":3,"10":4,"11":3,"12":1},
    tags: ["culture", "nature", "adventure"],
    jr_accessible: true,
    reservation_tips: "Kamikochi is open mid-April to mid-November only. No cars allowed — take the bus from Matsumoto.",
    accommodation_zones: [
      { name: "Near Matsumoto Castle", description: "Central, walking distance to castle and shopping streets", best_for: ["convenience", "culture"] },
    ],
    image: "https://plus.unsplash.com/premium_photo-1724336774996-4c9e00ed53df?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "sendai",
    name: "Sendai",
    region: "tohoku",
    description: "The largest city in Tohoku, known for gyutan (beef tongue), Tanabata festival, and gateway to Matsushima Bay.",
    highlights: ["Matsushima Bay", "Gyutan (beef tongue)", "Zuihoden Mausoleum", "Jozenji-dori Avenue", "Tanabata Festival (Aug)"],
    best_seasons: ["summer", "autumn"],
    crowd_level_by_month: {"1":1,"2":1,"3":2,"4":3,"5":3,"6":2,"7":3,"8":5,"9":2,"10":3,"11":2,"12":2},
    tags: ["food", "culture", "nature"],
    jr_accessible: true,
    reservation_tips: "Tanabata Festival (Aug 6-8) requires very early hotel bookings. Matsushima Bay is a 30-min train ride.",
    accommodation_zones: [
      { name: "Sendai Station area", description: "Central hub with great restaurant selection and transit access", best_for: ["convenience", "food", "transit"] },
    ],
    image: "https://plus.unsplash.com/premium_photo-1722872944372-3fac47ddb569?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "furano-biei",
    name: "Furano & Biei",
    region: "hokkaido",
    description: "Rolling hills of lavender fields and patchwork farmland. Stunning in summer, great skiing in winter.",
    highlights: ["Farm Tomita lavender fields", "Blue Pond", "Patchwork Road", "Furano Ski Resort"],
    best_seasons: ["summer", "winter"],
    crowd_level_by_month: {"1":2,"2":2,"3":1,"4":1,"5":2,"6":3,"7":5,"8":4,"9":2,"10":2,"11":1,"12":2},
    tags: ["nature", "adventure", "skiing"],
    jr_accessible: true,
    reservation_tips: "Lavender peaks mid-July. Rent a car for Biei — public transport is limited.",
    accommodation_zones: [
      { name: "Furano town", description: "Central base for both summer flower fields and winter ski", best_for: ["convenience"] },
    ],
    image: "https://images.unsplash.com/photo-1626911635167-0b3006fbda39?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "onomichi",
    name: "Onomichi",
    region: "chugoku",
    description: "Charming hillside port town and starting point of the Shimanami Kaido cycling route across islands to Shikoku.",
    highlights: ["Shimanami Kaido cycling", "Temple Walk", "Onomichi Ramen", "Senko-ji Temple & Ropeway", "Cat Alley"],
    best_seasons: ["spring", "autumn"],
    crowd_level_by_month: {"1":1,"2":1,"3":2,"4":3,"5":3,"6":2,"7":3,"8":3,"9":2,"10":3,"11":3,"12":1},
    tags: ["adventure", "culture", "food", "nature"],
    jr_accessible: true,
    reservation_tips: "Rent bikes for Shimanami Kaido at the terminal — reserve online in peak season.",
    accommodation_zones: [
      { name: "Onomichi hillside", description: "Atmospheric old town with temple walks and sea views", best_for: ["culture", "budget"] },
    ],
    image: "https://images.unsplash.com/photo-1574063480530-e00a945bf53c?w=800&h=500&fit=crop&q=80",
  },
  {
    slug: "ito",
    name: "Ito",
    region: "chubu",
    description: "Laid-back hot spring resort town on the Izu Peninsula with a volcanic coastline, fresh seafood, and surprisingly lively nightlife.",
    highlights: ["Ito Onsen", "Jogasaki Coast", "Kinmedai seafood", "Local nightlife bars", "Izu ocean views"],
    best_seasons: ["spring", "autumn", "winter"],
    crowd_level_by_month: {"1":2,"2":2,"3":3,"4":3,"5":3,"6":2,"7":4,"8":4,"9":2,"10":3,"11":3,"12":2},
    tags: ["onsen", "nightlife", "food", "nature"],
    jr_accessible: true,
    reservation_tips: "Book ryokans with private onsen ahead for weekends. Most restaurants are walk-in.",
    accommodation_zones: [
      { name: "Ito Station area", description: "Central location near nightlife and restaurants with easy train access", best_for: ["nightlife", "convenience", "first-timers"] },
      { name: "Jogasaki coast", description: "Quieter area near the dramatic coastline with ocean-view ryokans", best_for: ["nature", "couples", "onsen"] },
    ],
    image: "https://images.unsplash.com/photo-1614832360890-6a0d5171bd49?w=800&h=500&fit=crop&q=80",
  },
];
